### ISSUE TITLE
Add AppData file

### ISSUE THREAD

**Issue by jsbackus** [Ryochan7/antimicro#159]
Fedora (and perhaps other distros?) is going to require applications to ship with a proper [AppData]( http://people.freedesktop.org/~hughsient/appdata/) file in order to be listed in the Gnome Software Center. Additional information in [this](https://lists.fedoraproject.org/pipermail/devel/2014-January/194251.html) post.

Still looking into requirements. I'll take a stab at generating one, as life allows. Adding the issue to keep me honest. :)

**Comment by jsbackus** [comment]
Alright, sorry for the long delay. Appdata file is working fine but you need Gnome 3.14 or later to view it, I believe. 3.10 won't pick up files in the local cache and 3.12 wouldn't start at all. To view the appdata file, you need to start the Gnome Software center from a terminal with the following command-line:
    gnome-software --prefer-local

Will need translations. To translate, copy the en.po file in other/appdata/PO_files to <lang>.po and edit. The CMakeLists.txt file in other/appdata will need modified to parse the new .po file.

I'll generate a pull request with the changes.

**Comment by Ryochan7** [comment]
That's okay. I will take a look into the changes in the next day or so.

One problem regarding testing on my side is that I have Gnome 3.10 installed on my system since I am still using Fedora 20. There hasn't been a compelling reason for me to update to Fedora 21 since 20 works well enough for my needs.
