### ISSUE TITLE
Option to send mouse inputs as a mouse device for compatability with certain programs.

### ISSUE THREAD

**Issue by SolubleShoe** [Ryochan7/antimicro#169]
For games I sometimes want to have my controller act as an actual mouse. 

![image](https://cloud.githubusercontent.com/assets/10406596/5618402/f8c59766-9518-11e4-8188-c074c6e60b88.png)

**Comment by Ryochan7** [comment]
I'm not sure if that is possible with a user space application on Windows. As far as I know, none of the alternative mapping applications have that type of functionality. All the main gamepad mapping programs that I have played with use either SendInput or the lower level keybd_event and mouse_event functions for emulating a keyboard and mouse.

**Comment by SolubleShoe** [comment]
[BetterDS3](http://betterds3.ciebiera.net/) can do it. Try sending an e-mail to the dev @ pciebiera@gmail.com and maybe he can tell you how he did it.

**Comment by Ryochan7** [comment]
It looks like that functionality is still handled by the main MotioninJoy driver and not by anything in BetterDS3 itself. I doubt that I would get any correspondence back from the MotioninJoy developers so that isn't an option. I would likely have to figure out a way to make it work on my own.

As it stands, I am not sure where this functionality would improve compatibility. On Linux, the only game that I have tested that requires a true virtual mouse in order to play it using antimicro is Warsow 1.51. The older XTest method that was used doesn't work with that version. Incorporating uinput support was still worth it and it works better than the old XTest method in many situations.

If I ever find a way to make a virtual keyboard and mouse device on Windows instead of relying on SendInput, I will consider adding that as an option in the program. This issue will stay open as a reminder to keep looking into it. I am sorry that I can't provide a real resolution to the problem at this time.

**Comment by Ryochan7** [comment]
I just recently discovered that the Logitech Profiler makes a virtual keyboard and mouse when it launches so I have something to test. It looks like writing a HID minidriver for Windows would be the only way to allow antimicro to have a virtual keyboard and mouse associated with it on Windows. I have looked over some source code and also documentation for the Windows Driver Kit and it is a bit too much for me to comprehend. This idea will be kept in mind for future development. However, I will close this issue for the time being.

For future reference, the vmulti project source code has been a pretty good reference.

https://code.google.com/p/vmulti/

**Comment by Ryochan7** [comment]
One extra note that should be made is that virtual keyboard events work in Magicka: Wizard Wars, when using the Logitech Profiler, even while EasyAntiCheat is enabled. It looks like making a virtual keyboard and mouse would allow antimicro to work around anti-cheat software. This should allow some games that block events from SendInput to be playable.

I still haven't had any luck actually getting something to work. I haven't even been able to build vmulti or get similar code samples included in the Windows Driver Kit to build and install properly.

**Comment by Ryochan7** [comment]
I have finally managed to get vmulti compiled and working so I can finally test it. It took some time to get it compiled with Visual Studio 2013 and Windows Driver Kit 8.1.

**Comment by Ryochan7** [comment]
Update. I have been experimenting with vmulti and it seems like it will be able to do the job. It doesn't seem like there will be a real performance difference when using vmulti for KB+M emulation as opposed to using SendInput. However, it could potentially allow for some functionality that can't really be done using SendInput. The two big cases would be allowing Alt+Tab to be simulated in Windows 8.1 and working around games that block the use of messages generated by SendInput.

At this point, I have only gotten basic KB+M support working; the main things missing are horizontal wheel support, a decent amount of key bindings, and being able to update the bindings using the GUI. There are still a lot of changes that will have to be done. One real big problem is that vmulti currently has to be run in Test Mode on Windows 8.1 because I have been using a self-signed certificate. If vmulti support is ever going to be included in antimicro, the driver would have to be signed so that it can be distributed properly. This is a similar problem to the one pointed out in issue #156.

As an aside, I should mention that enabling Test Mode only works somewhat since it appears that some games actually check if Test Mode is enabled and will refuse to run if it is enabled; an example that I have come across is Magicka: Wizard Wars.

**Comment by Ryochan7** [comment]
I guess that I should mention that I have forked vmulti in order to add some functionality. Some changes were needed in order to get vmulti support more in line with what is currently supported using SendInput.

https://github.com/Ryochan7/vmulti

**Comment by Ryochan7** [comment]
At this point, distribution is the main problem. Since most of the main functionality has been implemented, this issue is considered closed again.

**Comment by Ryochan7** [comment]
Update. There is a build of vmulti that has been signed and works in Windows 8.1; the build is included with Touchmote. After playing around with that project for a bit, I took a look at changing the vmulti client code that I had been using in antimicro in order to be able to connect to that build's devices. Unfortunately, some of the special bindings (multimedia keys primarily) are not implemented in that version of vmulti so SendInput would have to be used to simulate those key presses. Other than that, using vmulti works and it might be possible to include support for that build in the future.
