### ISSUE TITLE
(win) Error | install_extra_dlls Error 1

### ISSUE THREAD

**Issue by fohrums** [Ryochan7/antimicro#172]
<code>Windows 8.1 x64
</code>

<i>Antimicro has no windows installer so you have to build from source.</i>

https://github.com/Ryochan7/antimicro#building-under-windows

After completing <i>Building under Windows</i>
I get the <code>install_extra_dlls</code> error 
right at that very last <i>Build All</i>

**Comment by Ryochan7** [comment]
When I installed Windows 8.1 and started from scratch recently, I ran into an issue with the build script making a blank antimicro file when a directory should have been created. That might have something to do with this problem since the install target won't exist in that scenario. It wasn't something that I worried about looking into at the time since I was under the assumption that I was the only person that would build antimicro on Windows. I'll look into it.

**Comment by fohrums** [comment]
I'm on Windows 8.1 x64 too and this is the 'only' error I get.

I appreciate the opensource'ness but could there be an alternative download for windows?
-installer (.msi)
-installer (.exe)
-portable (.exe)

**Comment by Ryochan7** [comment]
The only option that I can see that is really missing is a 64-bit version of the program. Unfortunately, the toolchain that I use only supports building 32-bit versions of programs.

**Comment by Ryochan7** [comment]
I had looked into projects that aimed to provide a proper 64 bit MinGW build environment for Qt on Windows but I had no success actually building a 64-bit version of antimicro. However, I have stumbled upon a project that I had not seen before that worked for me. I need to look into it further. I am posting the project link here for future reference.

http://sourceforge.net/projects/qtx64/

**Comment by fohrums** [comment]
@Ryochan7 What did you use to input the CMakeLists.txt when the qt-x64 version was installed?

all was provided was:
-Qt Assitant
-Qt Designer
-Qt Linguist

**Comment by Ryochan7** [comment]
I plugged in the proper compiler and Qt library paths into the version of Qt Creator that is included with the official Qt development package. For reference, here is a list of the arguments that I am passing to CMake. 

-DCMAKE_PREFIX_PATH=C:\Qtx64\qt-5.4.0-x64-mingw492r0-sjlj\qt-5.4.0-x64-mingw492r0-sjlj -DCMAKE_BUILD_TYPE=Debug -DPORTABLE_PACKAGE=OFF -DCMAKE_INSTALL_PREFIX=C:\Users\Travis\Downloads\antimicro\antimicro

I didn't use the default installation path for Qt-x64 since I wanted to keep Qt-x64 isolated from the main Qt development package.

There are a few paths in the main CMakeLists.txt file that assume x86 paths for some libraries. The project will have to be updated so that those library paths can be changed as needed.

**Comment by Ryochan7** [comment]
I have added a TARGET_ARCH variable to CMake in order to work around the library problem.

**Comment by Ryochan7** [comment]
I have finally gotten back around to testing the root problem again. The issue was due to the copy command that was being used in cmake for the **install_extra_dlls** step. If the install_extra_dlls step is checked before the install step in Qt Creator, the installation directory might not exist so the copy command will fail. The copy command used in the install_platforms_dll actually creates the directory if it doesn't exist. An extra command has been added to the install_extra_dlls step to create the installation directory if it does not already exist. This issue is now closed. Thank you fohrums for mentioning this.
