### ISSUE TITLE
PS2 controller, d-pad problem

### ISSUE THREAD

**Issue by antonisv** [Ryochan7/antimicro#175]
Hi i am trying to solve a ps2 controller issue. The problem is that when its pluged, all the directions on the d-pad are mapped to the "Geuide" key. All other buttons, are mapped ok including the two sticks. But the d-pads are all mapped on that "Guide" key. The L1,L2,R1 and R2 keyw are assigned to the d-pad....  How can i change that behavior? 

In addition the first time i press the d-pad, the key stays pressed forever until i unplug the controller. Any thoughts on that also wellcome... 

Thanks

**Comment by Ryochan7** [comment]
I would think that the first problem might be due to an improper mapping string. Can you open the Controller Mapping dialog window to see what mapping is currently being used? I would also suggest that you check out the Properties window to see how the controller events are displayed there.

As for the keys getting stuck, I am not sure what would be causing that to happen. As long as SDL sees that the dpad buttons have been released then antimicro should release the corresponding controls in the program. If there is a problem within antimicro, it might be due to the recent unplug workaround that will have release events ignored if SDL returns appropriate release events for all gamepad controls in one poll event. If that happens and no SDL_JOYDEVICEREMOVED event happens then that could cause that type of problem. I will look into that.

**Comment by Ryochan7** [comment]
Since there has been no update on this issue, I will close this issue. Hopefully the unplug event routine change helped.
