### ISSUE TITLE
DS4 bluetooth vs. cable

### ISSUE THREAD

**Issue by esbennn** [Ryochan7/antimicro#176]
Hello!

Just found this gem a few days ago and are now using it with my DualShock 4.
It's great!
Theres a small thing though - when I connect my controller via usb, it shows up correctly as a PlayStation 4 Controller. But when i connect it with bluetooth, it shows up as simply Wireless Controller. In this mode the analog sticks do not show up as sticks (the same way that the DPad does) - only as axes, making it a bit harder to customize dead zones, max zones, etc.
Is there any way I can force the device to be recognized as a PS4 controller when connected via bluetooth?

**Comment by Ryochan7** [comment]
Although this issue is closed, I will post something here in case other people possibly find this issue via a Google search later. I would assume that the generated GUID for the DS4 might be different when the controller is connected via bluetooth as opposed to USB. SDL probably didn't have a Game Controller mapping for your DS4 when in bluetooth mode so antimicro would revert to using the generic joystick mode. The Game Controller Mapping window in antimicro can be used to create an SDL 2 Game Controller mapping string so that antimicro will know which axes are mapped to the analog sticks and which controls are used for the dpad.
