### ISSUE TITLE
Xbox 360 Controller only detected under Root?

### ISSUE THREAD

**Issue by Xylemon** [Ryochan7/antimicro#177]
I have an issue under Slackware 14.1, where AntiMicro (I'm using version 2.10.1) only detects my controller under Root. Any ideas?

**Comment by Ryochan7** [comment]
Does your Xbox 360 controller work with other applications under your normal user? Can you check the permissions of the device? I would assume that Slackware might be set up so that your normal user does not have permission to actually use the controller. If that is the case, you will likely have to create a new udev rule in order to ensure that the device will be accessible by your normal user so you won't have to run antimicro as root

**Comment by Xylemon** [comment]
Yep that was the case, after following this: https://www.linuxquestions.org/questions/slackware-14/steam%27s-big-picture-mode-not-detecting-xbox-360-controller-on-slackware-14-a-4175479923/

I no longer have this problem. Thanks!
