### ISSUE TITLE
Buttons are not reevaluated after switching sets

### ISSUE THREAD

**Issue by pfanne** [Ryochan7/antimicro#179]
I'm using an xbox controller in windows.
I mapped "W" to my left analog stick in set 1 and the same in set 2.
Mapped changing to set 2 while holding my left bumper.
When I now start running using the left analog stick and press the left bumper to change to set 2, the character will stop moving.
The character will only start running again, when I slightly wiggle the analog stick or press any other button on the controller (generating input events). My guess is that the current button states of the newly selected set are not evaluated since there are no new events being generated which would trigger the reevaluation.

I tried this in multiple games with version 2.11 and 2.12.

Here is the profle I used:
http://pastebin.com/3N9MiXs8

**Comment by Ryochan7** [comment]
This problem would have been introduced when stick and dpad events started to get queued instead of executed immediately. As it was, the stick would be flagged as having a pending event to execute but nothing would execute it. Another event such as an axis motion or a button event would cause the pending event to finally be evaluated.

The set changing routine has been updated to execute any pending events for the sticks and dpad. Thank you for mentioning this problem.
