### ISSUE TITLE
Key Repeat as a slot

### ISSUE THREAD

**Issue by george-alisson** [Ryochan7/antimicro#181]
It would be nice if the key repeat feature would be a slot. That way, only buttons set to repeat would repeat, not all of them. That would be easy to implement. The device option should be kept too.

**Comment by Ryochan7** [comment]
That is something that I have thought about before but I haven't gotten around to implementing it. That is one nice feature in Pinnacle that people have used in profiles for added functionality.

**Comment by george-alisson** [comment]
I think I could implement it when I have time, but I have little experience with Qt.

**Comment by george-alisson** [comment]
Since you got confused in my other issue, maybe what I said does not make sense now, lol
I have no idea how Pinnacle works. How does it? Like turbo just for one single key? I'll try to implement this.

**Comment by Ryochan7** [comment]
It acts as turbo for a single key. Here is a screenshot for the Move Forward / Journal Up command from an Oblivion profile. It shows the Up arrow key being repeatedly pressed while the W key is held down until the corresponding button is released. That allows movement to work and item lists in shops to be scrollable.

![pinnacle_oblivion_press](https://cloud.githubusercontent.com/assets/581968/6912138/1e86dce4-d731-11e4-88e6-75dad02bff4f.png)

There are likely other cases where repeating single keys in a sequence could come in handy.

**Comment by george-alisson** [comment]
I've implemented a Repeat Last slot, which repeat the key in the slot before that. There can be multiple repeat slots, but only the last one will be active.

I have not figured how to make it work so that more than one key will be repeated without creating many timers and additional vars.

**Comment by george-alisson** [comment]
Sorry to bother you, but have you seen the commits at my fork? Do you have any idea how to make it repeat more than one key without using more timers?

It already works for one key at once anyways. So, should I create a pull request?

**Comment by Ryochan7** [comment]
I have been in a bit of a funk lately. Sorry about not getting back to you sooner. As for your question, there are probably a couple of different ways to go about it.

The first would be to make a static QList containing references to the relevant slots. Each slot could have a QTime associated with it that can be used to see how much time has elapsed between repeats. A static QTimer could be applied at the button level that will have a interval of less than 10 ms. The method that will be called will then go through the list and find which slots should be activated at that time and then reset the slot's QTime. For an example of something like this, you can take a look at the JoyButtonMouseHelper class along with the JoyButton::mouseEvent and JoyButton::moveMouseCursor methods.

Another way about it would be to have this done at the slot level. A QTimer would have to be associated with the slot and some other changes would have to be done so that a slot can handle generating events without the help of the JoyButton class.

A pull request would make integrating the changes a bit easier and you would be given credit in the repository history. The only thing that concerns me is that you currently have two QTimers being used to handle this functionality. As it is, it seems like a status flag and one QTimer should be all that is needed.

**Comment by george-alisson** [comment]
I'm short of time now, but I'll try to improve this soon.
