### ISSUE TITLE
Bash wrapper for antimicro with Steam games in Big Picture Mode on SteamOS

### ISSUE THREAD

**Issue by elmat0** [Ryochan7/antimicro#186]
How experienced are you with steam big picture mode? I have been experimenting with using antimicro with my xbox 360 (wireless) controller. I am trying to avoid the typical advice of 'just use xboxdrv' incase this method causes issues when I can finally get my hands on a steam controller.

Do you have any tips for creating a wrapper usable in the 'game launch options' from within big picture mode for native steam games? I have been experimenting and this is what I have come up with...

    #!/bin/bash
    # Requires 2 arguments. First the profile to apply then the game executable.
    PROFILEDIR="/etc/antimicro/profiles"

    antimicro --hidden --profile $PROFILEDIR/$1.gamecontroller.amgp & $2 && killall antimicro

My theory was I could then use something like the following in a games launch options.
```/etc/antimicro/steamwrapper halfway %command%```

However, although antimicro launches with the correct profile, then the game fires up, I can't seem to get antimicro to terminate once the game is closed. What's more, if I do 'kill antimicro' from a terminal, my control pad stops functioning in big picture mode alltogether.

Any tips?

**Comment by elmat0** [comment]
Aahh.. I finally figured out how to terminate antimicro after the game has closed. I have removed the 'killall antimicro' from the above script and instead set it into the game launch options like so.
```/etc/antimicro/steamwrapper halfway %command%; killall antimicro```

The second issue still remains though. After killing antimicro I appear to lose control of steam big picture mode. What is intriging is that if I am stuck like this, relaunching the game and exiting again appears to give me control back. I can keep on launching then exiting like this and I will regain control every second time. Perplexing.

The controller appears to still be recognised by steam when I look in settings -> controllers, though doesn't respond to any input. I understand this is likely an issue with Steam rather than antimicro though I'd still appreciate any insights you might have into how to debug or overcome this.

**Comment by Ryochan7** [comment]
I haven't used the proper steamos-session in some time but I remember having to work around quirks like that. When using SteamOS lately, I have been using a small custom Openbox + Compton session since it offers a bit more flexibility for running some desktop applications when needed. Also, I usually run antimicro from ssh using X tunnelling.

Although I have never tried that method of using antimicro in SteamOS, it seems like the command should work fine. I will have to play around with the steamos-session and try to see what could be causing problems. There only two things that I suspect might be contribute to the problems is no sleep command is used before the script ends or that using the tray icon is causing problems with the compositor in some way.

**Comment by Ryochan7** [comment]
I have been messing around with this and it is a good concept. I changed a few things in the script based on testing. One big problem with the original script is that command line arguments passed to games, within the %command% variable, are not carried over. With my current version, gamepad support works once a game exits and the Big Picture library interface comes up. Here is my updated version:

```
#!/bin/sh
# Requires 2 arguments. First the profile to apply then the game executable.
PROFILEDIR="/home/steam/antimicro profiles"

antimicro --hidden --profile "$PROFILEDIR/$1.gamecontroller.amgp" &
shift
"$@"; killall antimicro
wait
```

**Comment by elmat0** [comment]
Thanks @Ryochan7! I didn't even consider the normal command line options. Your updated version works much better. Much appreciated.

For what it's worth, I found it doesn't work with non-steam games added to BPM. I could be wrong though it appears to me that the %command% substitution feature isn't implemented for those. I came up with a clunky (albiet working) version that gets around that. Pretty much identical to the first one, though you have to jig around with the launch options syntax a bit. I suppose both methods could be combined into a single script to launch both steam or non-steam games, though I couldn't see a simple way to do it. Perhaps someone else can chime in here...

```
#!/bin/sh
#
# Requires 2 arguments entered in the games launch options, first the name of the antimicro profile
# to load, followed by the games executable. Due to the way SteamOS handles non-steam games
# (%command% substitution wont work) you must place an '&' at the start (or after any game launch
# options) to set the game as a background task, and a trailing ';' to encapsulate the antimicro
# options as a single command. The game executable specified at the end isn't actually called but
# merely to tell the script to keep antimicro running until that process is terminated.
#
# Syntax '<game launch options> & antimicro-nonsteam <profile name> <game executable> ;'
# eg '-r /home/steam/.neverball/Replays/Last.nbr & antimicro-nonsteam neverball neverball'

PROFILEDIR="/home/steam/antimicro/profiles"

antimicro --hidden --profile "$PROFILEDIR/$1.gamecontroller.amgp" &

GAMEPID=$(pgrep $2)
while [ -e /proc/$GAMEPID ]
do
  sleep 1
done

killall antimicro
wait
```

Offtopic: I am assuming that the steamcompmgr "single fullscreen window zoomed to fit" feature is what stops the antimicro gui working properly in BPM? If so, do you know of any workarounds for this? (other than your openbox/compton setup)

Further offtopic: Do you have a policy on accepting pre made profiles? I'm chipping away at making profiles for all of my mouse/keyboard SteamOS games. Happy to upload somewhere after I've polished them if you want.

**Comment by Ryochan7** [comment]
Thanks for looking into getting a wrapper working for added non-Steam apps.

A lot of desktop applications aren't really usable when using steamcompmgr. There are a couple of workarounds that could be used to launch the application and edit profiles. One workaround would require using Desktop mode and change some permissions so that the desktop user can generate events for the X display that is running the SteamOS session. uinput support could be used but that would require adding the desktop user to the steam group in order to access /dev/uinput. One downside is that I have not found a way to disable X pointer acceleration for the virtual mouse this way. You would have to disable pointer acceleration for the X session manually in the shell.

Pointing to the /home/steam/.Xauthority file when launching antimicro as the desktop user so that the desktop user can generate events on the X display running the SteamOS session. I wouldn't recommend that though.

One less painful workaround would be to make a script to launch a Xephyr session and run antimicro from within that session. Here is a link to a reference for how a script for running Xephyr would look: http://steamcommunity.com/groups/steamuniverse/discussions/1/620695877275390493/#c620695877306455248

**Comment by elmat0** [comment]
Ah sweet. I followed the Xephyr path. That fixes the crazy flickering from what I assume was fg/bg windows fighting for focus at least. 
 
Cheers for the link.
