### ISSUE TITLE
Working in SteamOS

### ISSUE THREAD

**Issue by formicsapien** [Ryochan7/antimicro#187]
Ryochan7,

I read your guide on getting antimicro installed in SteamOS.  It's perfect except for one flaw: you can use it while in the SteamOS user account.  I'm sure you know SteamOS won't let the user run multiple programs at the same time.  I found a workaround (or rather you did) on a post you made about getting mumble to work in SteamOS.  You have to add the command line to that file that determines what boots when you switch to SteamOS user (I forgot the file name).  The profile save must also be accessible by the SteamOS user so after a profile is created it must be moved using SU commands in the terminal

$ sudo cp \home\Documents\(file here) home\steam\Documents

After that in order to edit the profile you can do so in from the desktop, but you'll have to re move the file (made sure you overwrite with "-i") AND RESET the system (I have no idea why you have to reset for this as the orginal file should've been overwritten).

I recommend you add this stuff to your guide.

As always, thanks for everything, and sorry if this is in the wrong place.
-formicsapien

**Comment by Ryochan7** [comment]
There should probably be a section or a new Wiki page made mentioning ways to run the program in SteamOS since the process is a bit different than when using other Linux distros. In my case, I usually launch antimicro from an ssh session with X tunnelling enabled so that I can edit profiles on my laptop but events will be generated on my Steam box. That method doesn't help people that only have one computer accessible though. In issue #186, elmat0 has mentioned another method of running antimicro from within SteamOS without having to have custom bash scripts associated with each game.

**Comment by formicsapien** [comment]
I'll see if I can get my method on the wiki sometime, but you may want to look at it after I finish to see if it can be improved.
