### ISSUE TITLE
Cannot use Circumflex key

### ISSUE THREAD

**Issue by mihawk90** [Ryochan7/antimicro#195]
I think this problem is real this time :P 
So on a german QWERTZ keyboard, the Circumflex key is the one above the Tabulator key, I cannot set it in antimicro.

When I press it in the assigning window directly, nothing happens. When I hold it there, the window just closes without the key being assigned.

In the Keychecker, when tapping it once nothing happens.
When tapping it twice, this is the output:
![image](https://cloud.githubusercontent.com/assets/556162/8013372/f8023484-0bc8-11e5-97ad-1d0a6c2261bf.png)

When holding it, this is the output:
![image](https://cloud.githubusercontent.com/assets/556162/8013388/18546c5c-0bc9-11e5-85cd-12c0299fa685.png)

The Elder Scrolls Online and Guild Wars 2 both use it for the weapon swap, so it would be nice if this could be supported (I'm trying to get a profile for [this ESO Addon](http://www.esoui.com/downloads/fileinfo.php?id=1102#info) running).

**Comment by Ryochan7** [comment]
After looking into this, I would assume that no dead key would be interpreted properly in antimicro on Windows. This is a scenario that I have not encountered before so I will have to look into this further.

**Comment by Ryochan7** [comment]
Dead keys will have to start being handled differently than they are currently. Circumflex can now be assigned but you will have to press the circumflex key twice in order to assign that key. It seems like Qt does not pass dead key events to the application so antimicro will not see a single press of the key. Thank you for mentioning the problem with dead keys.
