### ISSUE TITLE
XBox button on XBox One controller not working under Windows 10

### ISSUE THREAD

**Issue by mihawk90** [Ryochan7/antimicro#196]
So yeah,
this is something I'm not sure you can do anything about it, but I'll still try my luck.

First off I have a Windows 10 (build 10130) machine and another Windows 8.1 Laptop (also a Windows 7 PC but this is unrelated).
On the Windows 8.1 machine the xbox button works just fine, it's recognized in antimicro at least (I didn't try binding anything on it but I assume this works when it's mapped).
On the Windows 10 machine however the xbox button doesn't seem to be working. In the Game Controller Mapping when I press the xbox button, nothing happens.

I cannot try an xbox 360 controller since I don't own one, but I suspect it would work.
The reason behind this is that apparently Microsoft changed how the XBone controller works under Windows 10, but not on Windows 8.

I know for a fact that they changed the Trigger buttons (they added another Axis on the right one and changed the values on the left one), so it might be the case that they also changed how the xbox button behaves, so that it might not function for external programs at all.
The reason for that is that the xbox button has a distinct use in Windows 10, it is used in fullscreen games to open the xbox bar (to record or take screenshots, later on maybe stream or whatever Microsoft comes up with).

I don't know if there is a way to work around this, but I wanted to let you know in case there is anything you might be able to do.
If there is anything I could test to help you on the issue, go ahead ask, I'll help top the best of my ability.

**Comment by Ryochan7** [comment]
Detecting the Xbox Guide button is handled by the SDL library that antimicro uses. I am assuming that Microsoft is probably shipping a different version of XInput in Windows 10 and that the behavior of the function that is used to detect presses of the Xbox Guide button has changed; I believe the GetStateEx function is the one that SDL uses to get the state of the Xbox Guide button. That function is technically a private function not mentioned in the public XInput API so Microsoft could have changed something.

If that is the case, I hope SDL gets updated to account for any new behavior. There isn't anything that can be done in antimicro to work around this problem in Windows 10. Since this would very likely impact Steam when running in Big Picture Mode on Windows, I would assume that this issue will be resolved well before Windows 10 is officially released.

**Comment by mihawk90** [comment]
Hm, well that's what I thought.
By the way it's not workiing in Steam either (neither normal nor Big Picture).
I would guess, as you said, it will be resolved before the release, we will see I guess :)

**Comment by Kaganis** [comment]
Having just upgraded to the release version of Windows 10 (64 bit), I've just hit this problem with an Xbox 360 controller.  Any suggestions to fix this?  My use case is minimising keyboard use due a health issue & that button loss is really painful.

**Comment by Ryochan7** [comment]
Although I haven't been working on this project much lately, the problem in this issue has mainly been a waiting game. This issue is pretty much fixed with updated code in SDL that will eventually be included in SDL 2.0.4. However, the current official stable release is still version 2.0.3. Maybe I should just compile the latest code and include that library for the next version.

**Comment by Kaganis** [comment]
That's good news, ta!  I'm fine with waiting, now that I know there's a fix somewhere in the pipeline.  :-)

**Comment by Ryochan7** [comment]
http://libsdl.org/download-2.0.php has been updated and SDL 2.0.4 is now the currently supported version. I guess I don't have to worry about building it myself now. That version will be tested to make sure there are no regressions; although, there shouldn't be any since the relevant public API has not changed.
