### ISSUE TITLE
Changing Volume under Windows 7

### ISSUE THREAD

**Issue by NeedForMirrors** [Ryochan7/antimicro#199]
Hey there, I'm using antimicro more as a remote control for my pc than actually gaming with it. Using the Xbox 360 controller I couldn't find a way to change the system volume. Is there any way to do this via macros? If not, do you plan on including this function in the future?

Really liking the program so far, keep it up!

**Comment by ssokolow** [comment]
In theory, the simplest solution would be to have antimicro fake presses on the Volume Down and Volume Up multimedia keys (internally known as `XF86AudioLowerVolume` and `XF86AudioRaiseVolume` here on Linux) and let volume control be handled by a more appropriate subsystem.

In practice, AntiMicro doesn't seem to provide a way to set those keys if they're not physically present to be pressed. (I could only confirm it would accept them by pressing them on my ATi Remote Wonder II remote control)

**Comment by Ryochan7** [comment]
Using media keys works fine although those keys are not present on the virtual keyboard in the edit button window. You would have to open the edit button window and press the key on a physical keyboard in order to assign volume keys to a button. I use an Xbox 360 controller for browsing YouTube on the HTML 5 app often so I have those keys linked in my media profile.

**Comment by NeedForMirrors** [comment]
Thanks for the quick answer. I tried pushing the hotkeys on my keyboard, but unfortunately it uses a combination of a special "fn" key in addition to F1-F12 (like this one: http://upload.wikimedia.org/wikipedia/commons/7/78/Keyboard_fn_key.png). The fn key alone isn't recognized by the program and the combination just leaves the set key empty.

**Comment by ssokolow** [comment]
I'm not hugely familiar with Windows but, on Linux, there are two reasons that might happen:

1. They are handled at the BIOS level and directly control the sound chip's mixer settings with any OSD or other reaction from the GUI being accomplished via "Volume was changed" notifications rather than by actually seeing the key events.

2. The system component which reacts to the key presses is removing them from the input queue to ensure that some other application doesn't also react them and produce weird "reacted twice to one event" bugs.

On my system, I had to deal with #2. antimicro and the xev input event viewer normally can't see those keypress events because Audacious Media Player (which handles volume control for me) grabs the keys exclusively using `XGrabKey`.

**Comment by NeedForMirrors** [comment]
I guess it's #2, but im not sure how to solve it. I guess I will have to install some hotkey program that enables me to change volume with other hotkeys and then bind those to the controller.

**Comment by ssokolow** [comment]
Just ask someone with a Windows machine (not me) and a multimedia keyboard to set up a config with those keys bound and send it to you. Then you can copy-paste the relevant bits into your config.

(Heck, if you tell them which buttons to bind them to, you could do no manual editing at all and just create your configs by loading what they sent you as a starting point and reconfiguring the other buttons.)

**Comment by Ryochan7** [comment]
I will add a small submenu to the virtual keyboard tab that will define some common multimedia keys. As for what can be done right now, you can check out the Browser Media Play profile in the antimicro-profiles repository. It has Volume Up, Volume Down, and Mute mapped. Unfortunately, you will have to edit your profile manually after adding a placeholder slot and put in the appropriate code within the code tag.

Volume Down:
https://github.com/Ryochan7/antimicro-profiles/blob/master/applications/Google%20Chrome/sdlgamecontroller/Browser%20Media%20Play.gamecontroller.xml#L464

Volume Up:
https://github.com/Ryochan7/antimicro-profiles/blob/master/applications/Google%20Chrome/sdlgamecontroller/Browser%20Media%20Play.gamecontroller.xml#L482

Mute:
https://github.com/Ryochan7/antimicro-profiles/blob/master/applications/Google%20Chrome/sdlgamecontroller/Browser%20Media%20Play.gamecontroller.xml#L384
