### ISSUE TITLE
Feature suggestion: reduce latency

### ISSUE THREAD

**Issue by WAZAAAAA0** [Ryochan7/antimicro#202]
Gamepad emulators such as AntiMicro, JoyToKey, Xpadder, Pinnacle and even AutoHotkey seem to have a certain degree of latency on emulating keyboard events. Of all the above, only JoyToKey has an interesting approach to reduce this delay, and it would be great to have it implemented in AntiMicro too!
![latency](https://cloud.githubusercontent.com/assets/12662809/8393620/e7b008d0-1d17-11e5-9778-7c54741cb4ff.png)

No need to read what follows, the first part is self-explanatory anyway, just for completeness' sake:
This is how I've setup the test in Dead or Alive 5 Last Round, a fighting game (genre which often requires flawless execution). In this specific game, if a controller is plugged in after the game starts, I can control both player 1 and 2 with a single controller, but one of them needs to use a gamepad emulator software, which is what I did, so I started to trade some blows using the same character with the same attack. The possible outcomes were always 2: both players get hit at the same time, or the native controller wins by 1 frame (sometimes 2 with AutoHotkey). The game runs at 60FPS.

Here some example videos:
Player 1 Blue busa = gamepad emulator software
Player 2 Santa busa = natively detected controller
first video, with AntiMicro, native wins 18 times out of 50 attempts: https://d.maxfile.ro/mjfxjcwfqb.mp4
second video, with JoyToKey at x16, native wins 2 times out of 50 attempts: https://d.maxfile.ro/ggbzcwkdjl.mp4

**Comment by Ryochan7** [comment]
Unfortunately that is part of the problem with using a piece of software for emulating keyboard and mouse events. Depending on how various systems and event loops behave, there is a strong possibility of encountering at least 1 frame worth of lag at times; any more lag than that would be considered a problem. When doing keyboard and mouse emulation in hardware like the Steam controller, that type of problem should pretty much be avoided.

The problem seems like it might be due to how often the gamepad is polled. antimicro uses the default poll rate of 10 ms that is set in SDL. The processing speed option in JoyToKey seems like it would mainly affect the gamepad poll rate. It has been a while since I have played with JoyToKey but I believe that Normal speed = 16 ms poll rate and x16 = 1 ms poll rate. Although it doesn't seem like SDL provides a direct way to change the gamepad poll rate using either SDL_WaitEvent or SDL_WaitEventTimeout, it wouldn't be hard to implement something equivalent that would use a different gamepad poll rate. I will have to play with that and see how the program behaves. Being able to change the gamepad poll rate could be an option in the next release.

**Comment by WAZAAAAA0** [comment]
That would be a great addition, good luck with it.

**Comment by Ryochan7** [comment]
The changes are pretty much in place for reducing the gamepad poll rate. I haven't done any form of comparison like you did using Dead or Alive 5. Maybe I should install SF IV and use that to compare the performance.

**Comment by Ryochan7** [comment]
The version 2.16 builds should be out in the next day. I couldn't really see a difference when testing out SF IV but I feel that it helped out a little bit when doing a True Vault Hunter run on Borderlands 2 recently. As an aside, it took a little bit to find an easy route to disable controller support so that the native gamepad support and antimicro wouldn't conflict.

**Comment by WAZAAAAA0** [comment]
This is great to hear. I'll make sure to try out the 2.16 and post a third video test.

**Comment by WAZAAAAA0** [comment]
Absolutely fantastic results, out of 500 punches thrown, all of them traded (which means they happened at the same time for the game). I only bothered to record 50 and did some random stuff for the rest of the brief video. https://d.maxfile.ro/vxlcrwqdzk.mp4
It's better than JoyToKey at x16 somehow, good job for such a quick implementation.

For all this time, antimicro.exe never reached my CPU usage of 1% with the polling rate set to 1ms, the CPU was similar to simply running Windows Task Manager or Process Hacker, negligible, I'm all for making 1 or 2 the default.

**Comment by Ryochan7** [comment]
That is good news. However, changing the default poll rate might not work out so well for some systems depending on the hardware and OS being used. The scheduler used for older versions of Windows would probably have problems although I haven't tested that. On the Linux side, the kernel version that is being used by a distribution matters a lot.

For example, SteamOS Brewmaster uses a 3.18 kernel and using a 1 ms poll rate causes antimicro to utilize a whole CPU core. However, on my Sabayon system running kernel 4.0, using a poll rate of 1 ms results in about 1% overall CPU usage. I think I remember noticing lower CPU usage when using Fedora 21 as well when playing around with the mouse refresh rate setting.

Currently, I am using a poll rate of 4 ms while using antimicro on SteamOS. During testing, the quickest time that events were actual detected from my Xbox 360 controller was around 3 - 4 ms.

**Comment by WAZAAAAA0** [comment]
I know this has nothing to do with the development of antimicro and I'm sorry for it, but since there's no private messaging anymore on GitHub, I just wanted to thank you again for your efforts and tell you about a video I recently made thanks to your tool. It was also featured on EventHubs (one of the two main websites dedicated to fighting games). I took the chance to "advertise" antimicro a bit at the minute 4:16 of such video, and made sure that the download link in the video description pointed at the donation page, huehue.

http://www.eventhubs.com/news/2015/aug/11/glitch-dead-or-alive-5-last-round-can-cause-33-life-bars-worth-damage-and-its-hilarious-watch/

**Comment by Ryochan7** [comment]
Thanks for the shoutout. I haven't really paid attention to SRK or Level|Up lately but I still check them out every once in a while.

I still try to keep my online presence to a minimum so I am kind of glad that there is no private messaging functionality on GitHub.

**Comment by ssokolow** [comment]
I preferred it when GitHub did have PM functionality because it meant I could keep a low profile and people could still contact me about things things inappropriate for the issues system.
