### ISSUE TITLE
Simulation of XInput and DirectInput

### ISSUE THREAD

**Issue by Papermanzero** [Ryochan7/antimicro#209]
It would be great if antimicro can also be used to map Xinput, DirectInput or both commands to keyboards/mouse and controllers.

E.g. 
XInput.A will be pressed with Keyboard.Enter
DirectInput.A will be pressed with Keyboard.Enter
DirectInput.A and XInput.A will be pressed with Keyboard.Enter
DirectInput.A will be pressed with with XInput.A
XInput.A will be pressed with DirectInput.A

**Comment by Ryochan7** [comment]
Having mixed input options would be a good idea but implementing it might not be so easy. I have been messing with something similar using xboxdrv for creating a virtual Xbox 360 controller with the right stick stuck at 0 and then using antimicro for assigning the right stick to mouse emulation. Playing Shadow Warrior (2013) with that configuration worked pretty well. That functionality would be possible to implement on Linux but getting that functionality implemented on Windows would be a much bigger problem.

**Comment by Ryochan7** [comment]
Exclusive controller access would be required in order for this functionality to work. The original controller would have to be hidden from other applications in order to not have a double input conflict in games. On Linux, this is possible with a couple of tweaks. Grabbing a joystick device is not enough for some games since the device can still be seen although they will not be able to read events from a device; some games will behave very weirdly when doing this. Performing a chmod on the original joystick device is necessary in order for other applications to not see the device at all. Using that tweak will allow for mixed controls to work on Linux and it works pretty well. It is becoming my preferred way to play games that have controller support.

This matter looks like it is even a bigger problem on Windows especially since exclusive device access is busted in Windows 10. I have read conflicting reports about whether grabbed devices can still appear when performing device enumeration. As it is, I am not sure that this functionality would be entirely possible with Windows. Using a library override like x360ce isn't really a full solution either. It seems like the only real way to make this work properly on Windows is at the hardware level like the Steam controller will be able to perform.

At this time, I will close this issue. If some method is discovered that works then this issue could be re-opened. This feature could be implemented in Linux only but I am not sure there is really a demand for it. I could post the xboxdrv config file that I am currently using if anyone is curious.

**Comment by ssokolow** [comment]
> I could post the xboxdrv config file that I am currently using if anyone is curious.

Please do. I have a Saitek Cyborg 3D USB Gold that I can't use with Strike Suit Zero because evdev, the game, and the joystick itself have all abdicated the responsibility for calibration. (The Joystick hardware is off-center when at rest, SSZ insists on evdev, evdev has no calibration support, and the lack of calibration makes SSZ's axis remapping GUI unusable as one final "#$%^ you".)

(At the moment, I'm using a Logitech joystick without rudder control or a hat switch that I picked up for $5 via a classified ad.)

**Comment by Ryochan7** [comment]
It probably won't help with your problem that much but I will post my test config file. It relies on reading the evdev events generated by the real Xbox 360 controller and then mapping it to a virtual Xbox 360 controller that xboxdrv creates. By default, the right stick is stuck at 0 so to not interfere with antimicro mapping the right stick of the original device to mouse emulation. Holding left bumper allows the right stick to be used in game for the Shadow Warrior 2013 radial menu and it switches antimicro to a blank set so there is no interference.

https://gist.github.com/Ryochan7/5758f88a9a9f75760972

A couple of small scripts are used as well to perform the chmod on the devices. The steam user on my Steam Box owns all joystick devices so sudo is not needed. Both xboxdrv and antimicro have to be running before running the disablegamepad script and then the game can be launched.

**disablegamepad**

    #!/bin/bash
    
    chmod 000 "/dev/input/by-id/usb-©Microsoft_Corporation_Controller_03C20DE-event-joystick"
    chmod 000 "/dev/input/by-id/usb-©Microsoft_Corporation_Controller_03C20DE-joystick"

**enablegamepad**

    #!/bin/bash
    
    chmod 660 "/dev/input/by-id/usb-©Microsoft_Corporation_Controller_03C20DE-event-joystick"
    chmod 660 "/dev/input/by-id/usb-©Microsoft_Corporation_Controller_03C20DE-joystick"

**Comment by ssokolow** [comment]
Thanks. Having a working starting point will really help me figure out how to get the config I want.

**Comment by Papermanzero** [comment]
Maybe the guy from WiinUSoft could support. He had the same issues.
http://www.wiinupro.com/home

**Comment by Ryochan7** [comment]
The biggest problem is dealing with the issue that Windows already sees the device as a game controller. When taking an old DirectInput compatible device and then mapping the controls to a virtual Xbox 360 controller, games that support both XInput and DirectInput will see two controllers. Depending on the game, a double input issue can occur so games will, for the most part, be unplayable. Opening the device in exclusive mode is what some projects, such as DS4Windows, use to attempt to get around that problem but it looks like that technique has its own set of issues and it is currently not working in Windows 10. That has become a really big issue for a lot of users. I will keep track of the status of that issue with DS4Windows and similar projects.

The actual mapping to an Xbox 360 controller would likely be done using the SCP Driver package that is fairly popular among projects and WiinUSoft uses that library as well. I have looked into it before and it is a pretty good.
