### ISSUE TITLE
Program restarts every time booted up.

### ISSUE THREAD

**Issue by LagannX** [Ryochan7/antimicro#220]
Why does AntiMacro 2.18.2 restart every time I boot it up? I even tried clicking on a saved profile but all that does is restart the App Settings Wizard. Anyway to make a profile boot all the way up from the get go?

**Comment by Ryochan7** [comment]
The problem with the wizard popping up when not needed has been fixed in the current code base. The issue was due to two threads trying to read from the settings object at the same time. One thread would set the object to read from the Mappings section and the wizard would look for any keys defined in that section as a result. If no custom controller mappings were found then the wizard would appear.

I am still working on some other tweaks but a new release should be out within the next couple of days.

**Comment by LagannX** [comment]
Ok! Great. Thanks for the heads up! Great program by the way.

**Comment by Ryochan7** [comment]
Version 2.19 is out now.

**Comment by LagannX** [comment]
ok. thanks!

**Comment by lylebrown** [comment]
I'm was still encountering this issue with the latest release. I deleted the startup entry for antimicro, then created my own, and now I no longer have this issue. Maybe there's a problem with how that's created?
