### ISSUE TITLE
joystick interfaces get randomly removed, antimicro forgets axis throttle types configs after reconnect

### ISSUE THREAD

**Issue by kon14** [Ryochan7/antimicro#222]
I'm using a Logitech RumblePad 2, controller works fine with supported games/steam streaming/system. Today I was trying to get the controller working with Minecraft through antimicro and I got it to operate smoothly aver a bit of fiddling with sensitivities and presets.

My joystick events in /dev/input/ disappeared after a while so I disconnected the controller, replugged and reloaded controllers in antimicro. After replugging my controller the mouse cursor started forcing itself towards the bottom-right end of my screen. I initially thought the analog sticks were stuck though I soon noticed that wasn't the case. I managed to get the cursor to stabilize after holding the sticks towards north-west and tried to load my backup preset. 

That didn't work out, the throttle setting was still set to Positive Throttle (though I had not noticed yet) rather than my Normal.
After reading my preset file for minecraft I don't seem to be able to find any throttle type setting in it. Is it left out?

Setting the throttle type back to Normal fixed the problem, though after antimicro somehow got my joystick interface removed it was still back to Positive Throttle upon replugging :/

Perhaps I should have split this into two issues though with the first issue being too general and somewhat connected to the second I thought I'd submit them together.

So here's what's going on in each case:

- Axis Throttle Type:
There doesn't seem to be a throttle type setting for the axis in the preset configs thus the setting is not saved upon controller reloading.

- Joystick being removed:
I haven't been able to reproduce this in a reliable manner. It randomly occurs while using the controller with antimicro. 
Doesn't happen on native controller support/without antimicro running.
Seems to be extremely agressive and reproduceable on controller reloading (js events might be almost instantly removed! if they don't removed on reload they might do after pressing anything in antimicro window)

edit: using antimicro 2.10.1, I'll try building the latest version and reproducing, was axis throttle missing from preset files in 2.10.1? is it there now?

**Comment by Ryochan7** [comment]
Saving of axis throttle settings was an option with that version. Looking back at the source code for that version, most of those routines are mostly the same in the latest release. Normal throttle is the default throttle setting for an axis so that setting is not saved to a profile for that value. One thing that might be considered an issue is regarding any axis that might be detected as a trigger. If an axis has an initial value of -30,000 or below, antimicro will not use the throttle setting saved in the profile but instead set the throttle type to Positive throttle. Other than that, antimicro should use whatever throttle setting has been saved to a profile.

As for the joystick being removed problem, I wouldn't know what would have caused that problem. It does not sound like an issue that I have read about previously. antimicro does not interact with any js*/event* device directly but instead relies on SDL to interface with the controller. antimicro shouldn't cause any problem that would cause the actual device file to be removed from the system. My only suggestion would be to try out the latest version (2.19) and see if the problem still exists. If it does then that problem can be investigated further.

**Comment by kon14** [comment]
> If an axis has an initial value of -30,000 or below, antimicro will not use the throttle setting saved in the profile but instead set the throttle type to Positive throttle.

Are you talking about controller's hardware axis specs or the minimum throttle setting being set in antimicro? I'll try reproducing the issue with a ps3 controller and see how that goes.

> antimicro does not interact with any js/event device directly but instead relies on SDL to interface with the controller

that's what I expected, it just didn't seem random enough to blame it to sdl, could it be it manages to get udev to remove the interface :S 

I'll build the git version for my laptop and update on the axis throttle results.

**Comment by Ryochan7** [comment]
> Are you talking about controller's hardware axis specs or the minimum throttle setting being set in antimicro?

I was referring to the controller hardware axis value when the controller is first detected. SDL reads the initial state of the controller when it is first detected and those values get passed to antimicro.

> that's what I expected, it just didn't seem random enough to blame it to sdl, could it be it manages to get udev to remove the interface

I wouldn't think that SDL would cause this kind of problem either. What driver are you using for your controller? I would assume that it would probably be either xpad or xboxdrv.

**Comment by kon14** [comment]
> What driver are you using for your controller? I would assume that it would probably be either xpad or xboxdrv.

you would be right, it's xpad, though I doubt the interface is removed due to xpad. the controller works flawlessly with it save for when I try to get it working with minecraft with antimicro.

I'll try out a different controller once I'm back home, then I'll also give the git version a ride.

> I was referring to the controller hardware axis value when the controller is first detected. SDL reads the initial state of the controller when it is first detected and those values get passed to antimicro.

so if I got the following right

> If an axis has an initial value of -30,000 or below, antimicro will not use the throttle setting saved in the profile but instead set the throttle type to Positive throttle.

then checking my controller's default axis value with SDL_JoystickGetAxis should show me whether my joystick has such a negative value, resulting in antimicro not using the normal throttle setting?
