### ISSUE TITLE
block button press

### ISSUE THREAD

**Issue by AssFat** [Ryochan7/antimicro#232]
i use a cronus also and there are a few ways to block the actual game pad button from being sent to the game.
example: want a space bar press sent to game from tapping A on the controller, but dont want A sent as well.
is it possible with antimicro?
if im posting this type of thing in the wrong place please let me know. i looked for another forum.
thanx

**Comment by Ryochan7** [comment]
This isn't possible within antimicro. One workaround that is used to attempt to block access to a controller is enabling exclusive mode for a gamepad device. In antimicro, SDL is used to open gamepad devices and it has sole access to the native device handle being used. Enabling exclusive mode is not possible with this configuration. Performing device enumeration manually as well and enabling exclusive mode would likely cause SDL events to no longer be generated. All gamepad handling would have to be done by antimicro and routines would have to be made to perform device enumeration and device polling for each platform. Also, enabling exclusive mode is not really a complete solution as some games have problems with it.

On Linux, there are some small steps that can be done to stop an application from detecting a gamepad for situations when a game does not allow controller support to be disabled in game or if you want to mix input methods. I have taken advantage of that during my recent playthroughs of Shadow Warrior 2013 and Bioshock Infinite. For Shadow Warrior 2013, I was able to create a virtual controller using xboxdrv with the right stick disabled and antimicro was used to perform mouse emulation. Bioshock Infinite required that full KB+M emulation be performed due to the trigger issue with the port that has been fixed with the latest update. The left stick stops registering when using mouse buttons, even on a real mouse, so just mapping the triggers to mouse buttons was not an option.

On Windows, I have not found a solution that I really like. The closest workaround is to enable passthrough mode in x360ce and not bind portions of the gamepad that I don't want the game to detect (mainly the right stick). However, there is some input lag with that configuration that I have not found a way to avoid. For Windows, it really seems like going with a hardware based solution is the best way to go.

**Comment by AssFat** [comment]
have you ever used Cronus device? or Autohotkey? Cronus scripts may be interesting to you. and i could have sworn ive used AHK to block a button before. if i come across it or remember how, ill let you know. 
is there a spot on this site where i can download complex scripts? i like checking out what other people are doing with these types of apps.

**Comment by Ryochan7** [comment]
I haven't used a Cronus device before. It looks like the device runs a server that the client will use to send scripts to and the actual button translation happens on the device itself. The OS will see whatever device the Cronus is set to use. Although I have never had a use for Autohotkey, I am a little familiar with the program. It looks like Autohotkey uses the [BlockInput](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646290%28v=vs.85%29.aspx) Windows function in order to block input from keyboard and mouse events from the rest of the system.  The keys are then translated based on the running script and sent through SendInput so the rest of the system will detect the translated key.

I have taken a look into how DS4Windows and InputMapper use exclusive mode in an attempt to hide the original device and present Windows with an Xbox 360 controller. Even when exclusive mode is enabled, it seems like some games can still detect the original device and try to use it instead. I think I have read that some games will actually crash when exclusive mode is used. On Linux, devices locked with exclusive mode can still be detected but no events are generated for the device. Some games will still try to use the first controller detected and I think I have read about some games behaving erratically. When I want to perform mixed input, running chmod on the original devices before launching a game is enough to keep the original controller from getting detected.

I wish there was more information about the Steam controller. That really seems like it could pull off something great. It will be interesting to hear from people who receive the first batch of retail units in October.
