### ISSUE TITLE
Wireless PS3/PC Controller Right Analog Stick Malfunction...

### ISSUE THREAD

**Issue by nextdime** [Ryochan7/antimicro#242]
I have gotten myself a GameWare wireless receiver with a 2.4mhz usb receiver... all works fine except the right analog stick! It goes up and down only but not left and right!

I have tried a trial version of Pinnacle and Yes all works fine...

Any help on this?

Much appreciated

**Comment by Ryochan7** [comment]
The mapping for the controller is probably not right. You should open up the Game Controller Mapping dialog window and look at the mapping string being used. **rightx** is probably incorrect or not included in the mapping string. You might have to update the mapping being used. There will be a problem mapping the axis if the controller is in Game Controller mode though. The next version of antimicro should fix that problem.

**Comment by nextdime** [comment]
what is the mapping file called? i may update it manually - 

79000600000000000000504944564944,Generic   USB  Joystick  ,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a4,lefttrigger:b6,righttrigger:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,

63252305000000000000504944564944,PS3/PC WirelessGamePad,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:b0,righty:a2,lefttrigger:b6,righttrigger:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,

as you may have noticed all I could do is copy the correct mapping sequence into the PS3 controller for a fix...

**Comment by Ryochan7** [comment]
Mappings are saved under antimicro_settings.ini. The location of the file will depend on which operating system you are running. Since you appear to be using Windows, the file should be saved along the lines of `%LocalAppData%\antimicro\antimicro_settings.ini`.

Looking at the second string you posted, rightx is mapped to a button instead of an axis. For pasting the mapping string into the config file, you would have to make a new entry in the mapping group along these lines.

[Mappings]
63252305000000000000504944564944=63252305000000000000504944564944,PS3/PC WirelessGamePad,platform:Windows,a:b2,b:b1,x:b3,y:b0,back:b8,start:b9,leftshoulder:b4,rightshoulder:b5,leftstick:b10,rightstick:b11,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:b6,righttrigger:b7,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,

The key is the GUID generated by SDL and the value is the actual mapping string that will be passed to SDL.
