### ISSUE TITLE
Feature? Forum

### ISSUE THREAD

**Issue by ccomly** [Ryochan7/antimicro#244]
I think some kind of forum would be great for this, along with the profiles. For information, profile sharing etc. Or maybe irc on freenode or something. Feels wrong to ask about simple things in a github issue.

So ill do it this once im trying to do this basically.

hold button, hit x one time then hit/hold q until release, on release hit x again. 
cant figure out how to do it.

**Comment by Ryochan7** [comment]
There used to be a forum when I had my own web space. I really can't even afford a $5/month hosting plan so I don't see a forum being made any time soon. There is still a mailing list that hasn't really been used. https://groups.google.com/d/forum/antimicro-discussion (antimicro-discussion@googlegroups.com)

As for your mapping question, that should be possible. I think something along these lines should work.

    X -> Pause 00.00 -> Q -> Release 00.01 -> X

One thing to mention is that the *Pause 00.00* slot will cause a release event for preceding key slots to occur after those keys are active for a set period of time. You can possibly insert some Press Time slots in front of the X slots in order to change the amount of time X will be held before it is released; the default is around 100 ms.

**Comment by ssokolow** [comment]
Quality free forum hosting is one of the few things I haven't yet gotten around to researching for the big resources chart in my private "Development Policy" document but, for chat, might I suggest https://gitter.im/?

It's designed to provide an integrated chat experience analogous to what API hooks and GitHub Flavored Markdown bring to GitHub Issues, it's got both custom clients and an IRC bridge, and its monetized on a GitHub-like "public stuff is free forever, pay for private projects" freemium model.

**Comment by ccomly** [comment]
It worked fantastically  thank you!

**Comment by Ryochan7** [comment]
gitter.im looks like a pretty neat service. It could be useful for discussing smaller issues that would normally be filed as questions here. I am not sure about those forums though. Although ProBoards looks like it could be decent, the limits of the free plan, particularly regarding file attachments, might be a problem. Also, I think I would like to use open source forum software on my own space rather than use a service that uses a proprietary solution.

**Comment by Ryochan7** [comment]
I have made a Gitter chat room to test out the service. https://gitter.im/Ryochan7/antimicro

**Comment by ssokolow** [comment]
Just to cap off the topic, if you also want a forum, SourceForge's [`mod_php`-enabled web hosting](https://sourceforge.net/p/forge/documentation/Project%20Web%20and%20Developer%20Web/) would do the trick and, lately, they've gone out of their way to make it clear that, if you're choosing GitHub for what GitHub does better, you're still welcome to use SourceForge for things GitHub doesn't do. (open-source software catalogue/directory, mailing lists, PHP hosting, etc.)

**Comment by Ryochan7** [comment]
I don't really see a need for a dedicated forum. Especially with the official release of the Steam Controller and my own lack of involvement in this project over the past few months, antimicro should be considered a legacy option for playing Linux and Windows games with a controller. I think that it would probably be better to support Valve and their endeavours than to put too much more work into this project. There are a couple of problems that I want to fix in antimicro so there is enough justification for at least one more release. I will probably be able to get a Steam Controller around Christmas so I will probably not have a use for antimicro after that.

The community behind the Steam Controller has been doing some really great work. One really cool community project has been the community maintained database of controller configurations.

http://www.steamcontrollerdb.com/

**Comment by ssokolow** [comment]
You're talking to someone who would (and, for maybe 5 years, did) sooner stop gaming than install Steam and who went to a great deal of expense and effort to get genuine NES, SNES, Genesis, N64, PS2, Gamecube, Xbox 360, and Wii controllers and the hardware and software to attach them to a PC.

I may pick up a Steam controller for my input devices collection if my budget allows it, but I doubt I'll be using it much.
