### ISSUE TITLE
steam controller

### ISSUE THREAD

**Issue by ccomly** [Ryochan7/antimicro#264]
So i got my steam controller a while back and  the big picture controller configuration is decent, it however is missing cycling, i used to have my trigger do  12-cycle-13-cycle-14, the controller isnt picked up by antimicro, prob cause its tied into steam.

Might be the wrong place to ask but is it possible to like disable the controller for steam and just have it show up in antimicro as a regular controller? i cant figure out how to do cycling in big picture steam controller configuration. cheers.

**Comment by Ryochan7** [comment]
I don't have a Steam controller so I can only go by information given by Valve and the community using the controller; hopefully that will change soon. Based on the information that I have read, you would have to have the Steam controller set up to emulate an Xbox 360 controller and you also have to launch antimicro from Steam as a non-Steam app. It looks like what you want would not really be possible due to how the Steam controller is tied into the Steam client.

I guess that making a wrapper script would be possible but it doesn't seem practical. Hopefully Valve will add cycling in future firmware updates for the Steam controller. Valve added spring mode functionality recently (mouse regions) so there are still major features to be added to the controller. As an aside, I honestly don't know how someone would really be able to enjoy a game like Torchlight 2 with a controller without using something like the mouse regions feature.

**Comment by ssokolow** [comment]
As I understand it, the Steam controller appears to the OS as a keyboard and mouse, so Steam is needed to do the reverse of what Antimicro does.

I'd look into using [xboxdrv](http://pingus.seul.org/~grumbel/xboxdrv/xboxdrv.html) to generate a virtual 360 controller from it.

**Comment by Ryochan7** [comment]
I now have a Steam controller. I have only been playing with it for a couple of hours so I have some adjusting to do. Regarding the original question, it is possible to use antimicro with the Steam controller. When the Steam client is open and a Steam controller is connected, a virtual Xbox 360 controller will be created. You can then launch antimicro from Steam when using normal BPM mode, load the profile you want to use, and then launch whatever game you want to play; you have to be using a controller configuration that is emulating an Xbox 360 controller for the game that you are playing. That way, antimicro will have the correct mapping for the Steam controller and it will detect the events coming from the Steam controller.

If you are using the SteamOS session, you will have to use a wrapper such as the one posted in issue #186 in order to have antimicro launch along with the game that you want to play.

Also, for future reference, Steam passes an SDL_GAMECONTROLLERCONFIG string when launching games that contains a mapping for the Steam controller. By default, antimicro will use Joystick mode for the Steam controller if launched outside of Steam so it might be useful to post the mapping string here.

```
SDL_GAMECONTROLLERCONFIG=03000000de280000fc11000001000000,Steam Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,
```
